type NotionBlockTypes =
  | 'paragraph'
  | 'heading_1'
  | 'heading_2'
  | 'heading_3'
  | 'bulleted_list_item'
  | 'numbered_list_item'
  | 'quote'
  | 'to_do'
  | 'toggle'
  | 'template'
  | 'synced_block'
  | 'child_page'
  | 'child_database'
  | 'equation'
  | 'code'
  | 'callout'
  | 'divider'
  | 'breadcrumb'
  | 'table_of_contents'
  | 'column_list'
  | 'column'
  | 'link_to_page'
  | 'table'
  | 'table_row'
  | 'embed'
  | 'bookmark'
  | 'image'
  | 'video'
  | 'pdf'
  | 'file'
  | 'audio'
  | 'link_preview'
  | 'unsupported'

export default NotionBlockTypes
